[general]
hostname = "example.com"
recaptchaSecretKey = "123456"
listen = "127.0.0.1"
port = 8080

[database]
addr = "127.0.0.1:3309"
user = "root"
password = "123456"
databaseName = "oqs"

[redis]
addr = "127.0.0.1:6379"
password = ""

[logger]
error = "./test/errors.log"
normal = "logs.log"